[package]
name = "solidity-lsp-bench"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "bench"
path = "src/main.rs"

[[bin]]
name = "gen-readme"
path = "src/gen_readme.rs"

[dependencies]
serde_json = "1"
indicatif = "0.17"
console = "0.15"
